### ISSUE TITLE
great work .. can i use it for a production application ?

### ISSUE THREAD

**Issue by cayaner** [jeremykenedy/laravel-roles#1]
it's a **real** world implementation,
i loved the **levels** feature, giving permission to both role and **user**, and **clear** documentation. 

another question is it possible to check multi roles or permissions in middleware?

thanks in advance,,

**Comment by jeremykenedy** [comment]
Thank you,

Please do.

You you can check for multi roles and levels:

Multiple Roles:
```
if ($user->hasRole(['admin', 'moderator'])) {
    /*
    | Or alternatively:
    | $user->hasRole('admin, moderator'), $user->hasRole('admin|moderator'),
    | $user->hasOneRole('admin, moderator'), $user->hasOneRole(['admin', 'moderator']), $user->hasOneRole('admin|moderator')
    */

    // The user has at least one of the roles
}

if ($user->hasRole(['admin', 'moderator'], true)) {
    /*
    | Or alternatively:
    | $user->hasRole('admin, moderator', true), $user->hasRole('admin|moderator', true),
    | $user->hasAllRoles('admin, moderator'), $user->hasAllRoles(['admin', 'moderator']), $user->hasAllRoles('admin|moderator')
    */

    // The user has all roles
}
```

Multiple Levels Check:
```
if ($user->level() > 4) {
    //
}
```

If you needed another or a mix of checking I would try using the or `||` and the and `&&` operators and expand the conditional check.

**Comment by cayaner** [comment]
thanks ...

i was asking about  check multi roles or permissions in **middleware**
may be like this:
```php
Route::group(['middleware' => ['role:admin|manager']], function () {

});
```
Or
```php
Route::group(['middleware' => ['role:admin,role:manager']], function () {

});
```

**Comment by jeremykenedy** [comment]
You can totally check for multiple roles, you would just do as you have don in our first example using the pipe (|) operator.

```
Route::group(['middleware'=> ['role:admin|user']], function () {
```

**Comment by FarhanShares** [comment]
Old one though, but this can be added in docs too. Overall it's a great package.
