### ISSUE TITLE
how to create new role

### ISSUE THREAD

**Issue by lCHECHOl** [jeremykenedy/laravel-roles#10]
laravel 5.5 | vagrant/homestead

Hello, I would like you to help me explain how I can create a new role, and associate x permissions to that role, I saw the documentation of laravel-roles but I did not understand, thanks in advance

**Comment by xewl** [comment]
Essentially, if you follow these sections of the readme, you should have an understanding of how to accomplish this:
https://github.com/jeremykenedy/laravel-roles#creating-roles
https://github.com/jeremykenedy/laravel-roles#creating-permissions
https://github.com/jeremykenedy/laravel-roles#attaching-detaching-and-syncing-permissions

**Comment by jeremykenedy** [comment]
```

// Create New Role
$newRole = Role::create([
    'name' => 'New',
    'slug' => 'new',
    'description' => '',
    'level' => 1000,
]);

// Create New Permission
$viewStats = Permission::create([
    'name' => 'View stats',
    'slug' => 'view.stats',
    'description' => '', 
]);

// Attach persmission to role
$newRole->attachPermission($viewStats); // permission attached to a role
```

**Comment by lCHECHOl** [comment]
hola, creo que tengo problemas para trabajar con los roles, no se que estoy haciendo mal, en "PermissionsTableSeeder" tengo esto:

if (Permission::where('name', '=', 'Puede ver objetos sociales')->first() === null) {
        $viewSocialObjects =  Permission::create([
           'name' => 'Puede ver objetos sociales',
           'slug' => 'view.SocialObject',
           'description' => 'puede ver objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede crear objetos sociales')->first() === null) {
         $createSocialObjects = Permission::create([
           'name' => 'Puede crear objetos sociales',
           'slug' => 'create.SocialObject',
           'description' => 'Puede crear objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede editar objetos sociales')->first() === null) {
         $editSocialObjects = Permission::create([
           'name' => 'Puede editar objetos sociales',
           'slug' => 'edit.SocialObject',
           'description' => 'Puede editar objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede eliminar objetos sociales')->first() === null) {
         $deleteSocialObjects = Permission::create([
           'name' => 'Puede eliminar objetos sociales',
           'slug' => 'delete.SocialObject',
           'description' => 'Puede eliminar objetos sociales',
           'model' => 'Permission',
         ]);
       }       

en "RolesTableSeeder" tengo esto:

if (Role::where('name', '=', 'Admin')->first() === null) {
	        $adminRole = Role::create([
	            'name' => 'Admin',
	            'slug' => 'admin',
	            'description' => 'Admin Role',
	            'level' => 5,
        	]);
	    }

      if (Role::where('name', '=', 'Enterprise')->first() === null) {
	        $enterpriseRole = Role::create([
	            'name' => 'Enterprise',
	            'slug' => 'enterprise',
	            'description' => 'Enterprise Role',
	            'level' => 4,
        	]);
	    }

    	if (Role::where('name', '=', 'User')->first() === null) {
	        $userRole = Role::create([
	            'name' => 'User',
	            'slug' => 'user',
	            'description' => 'User Role',
	            'level' => 1,
	        ]);
	    }

    	if (Role::where('name', '=', 'Unverified')->first() === null) {
	        $userRole = Role::create([
	            'name' => 'Unverified',
	            'slug' => 'unverified',
	            'description' => 'Unverified Role',
	            'level' => 0,
	        ]);
	    }

en "ConnectRelationshipsSeeder" tengo esto: 

$permissions = Permission::all();


      /**
	     * Attach Permissions to Roles
	     *
	     */
		$roleAdmin = Role::where('name', '=', 'Admin')->first();
    foreach ($permissions as $permission) {
      $roleAdmin->attachPermission($permission);
    }

    $enterpriseRole = Role::where('name', '=', 'Enterprise')->first();
    $viewSocialObjects = Permission::where('name', '=', 'Puede crear objetos sociales')->first() === null;
    $createSocialObjects = Permission::where('name', '=', 'Puede crear objetos sociales')->first() === null;
    $editSocialObjects = Permission::where('name', '=', 'Puede editar objetos sociales')->first() === null;
    $deleteSocialObjects = Permission::where('name', '=', 'Puede eliminar objetos sociales')->first() === null;

      $enterpriseRole->attachPermission($viewSocialObjects);
      $enterpriseRole->attachPermission($createSocialObjects);
      $enterpriseRole->attachPermission($editSocialObjects);
      $enterpriseRole->attachPermission($deleteSocialObjects);

cuando corro los seeds me dice esto:

image
![image](https://user-images.githubusercontent.com/13172977/37432600-eaaa504e-27a6-11e8-8878-0a4309bdd1fd.png)

**Comment by jeremykenedy** [comment]
try checking against the slug before creating the new record. It may work better since that is a single string.

**Comment by lCHECHOl** [comment]
Hi, I think I have problems working with the roles, I do not know what I'm doing wrong, this is for an apirestfull

in "PermissionsTableSeeder" I have this:

`public function run()
     {

       /**
       * Add Permissions
       *
       */
       if (Permission::where('name', '=', 'Can View Users')->first() === null) {
        $viewUsers = Permission::create([
           'name' => 'Can View Users',
           'slug' => 'view.users',
           'description' => 'Can view users',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Can Edit Users')->first() === null) {
        $editUsers =  Permission::create([
           'name' => 'Can Edit Users',
           'slug' => 'edit.users',
           'description' => 'Can edit users',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Can Delete Users')->first() === null) {
        $deleteUsers = Permission::create([
           'name' => 'Can Delete Users',
           'slug' => 'delete.users',
           'description' => 'Can delete users',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede ver objetos sociales')->first() === null) {
        $viewSocialObjects =  Permission::create([
           'name' => 'Puede ver objetos sociales',
           'slug' => 'view.SocialObject',
           'description' => 'puede ver objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede crear objetos sociales')->first() === null) {
         $createSocialObjects = Permission::create([
           'name' => 'Puede crear objetos sociales',
           'slug' => 'create.SocialObject',
           'description' => 'Puede crear objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede editar objetos sociales')->first() === null) {
         $editSocialObjects = Permission::create([
           'name' => 'Puede editar objetos sociales',
           'slug' => 'edit.SocialObject',
           'description' => 'Puede editar objetos sociales',
           'model' => 'Permission',
         ]);
       }

       if (Permission::where('name', '=', 'Puede eliminar objetos sociales')->first() === null) {
         $deleteSocialObjects = Permission::create([
           'name' => 'Puede eliminar objetos sociales',
           'slug' => 'delete.SocialObject',
           'description' => 'Puede eliminar objetos sociales',
           'model' => 'Permission',
         ]);
       }       

     }`

in "RolesTableSeeder" I have this:

`  public function run()
    {
	    /**
	     * Add Roles
	     *
	     */
    	if (Role::where('name', '=', 'Admin')->first() === null) {
	        $adminRole = Role::create([
	            'name' => 'Admin',
	            'slug' => 'admin',
	            'description' => 'Admin Role',
	            'level' => 5,
        	]);
	    }

      if (Role::where('name', '=', 'Enterprise')->first() === null) {
	        $enterpriseRole = Role::create([
	            'name' => 'Enterprise',
	            'slug' => 'enterprise',
	            'description' => 'Enterprise Role',
	            'level' => 4,
        	]);
	    }

    	if (Role::where('name', '=', 'User')->first() === null) {
	        $userRole = Role::create([
	            'name' => 'User',
	            'slug' => 'user',
	            'description' => 'User Role',
	            'level' => 1,
	        ]);
	    }

    	if (Role::where('name', '=', 'Unverified')->first() === null) {
	        $userRole = Role::create([
	            'name' => 'Unverified',
	            'slug' => 'unverified',
	            'description' => 'Unverified Role',
	            'level' => 0,
	        ]);
	    }

    }`

in "ConnectRelationshipsSeeder" I have this:

`public function run()
    {

	    /**
	     * Get Available Permissions
	     *
	     */
		$permissions = Permission::all();


      /**
	     * Attach Permissions to Roles
	     *
	     */
		$roleAdmin = Role::where('name', '=', 'Admin')->first();
    foreach ($permissions as $permission) {
      $roleAdmin->attachPermission($permission);
    }

    $enterpriseRole = Role::where('name', '=', 'Enterprise')->first();
    $viewSocialObjects = Permission::where('slug', '=', 'view.socialobject')->first();
    $createSocialObjects = Permission::where('slug', '=', 'create.socialobject')->first();
    $editSocialObjects = Permission::where('slug', '=', 'edit.socialobject')->first();
    $deleteSocialObjects = Permission::where('slug', '=', 'delete.socialobject')->first();

      $enterpriseRole->attachPermission($viewSocialObjects);
      $enterpriseRole->attachPermission($createSocialObjects);
      $enterpriseRole->attachPermission($editSocialObjects);
      $enterpriseRole->attachPermission($deleteSocialObjects);
    }`

when I try with the company role to see a social object it tells me this:

![image](https://user-images.githubusercontent.com/13172977/37433923-d2b3896a-27ab-11e8-8053-4839af0dd3b8.png)


in the database I have the following

![image](https://user-images.githubusercontent.com/13172977/37433976-f8defbe2-27ab-11e8-8400-b51363f2eb6b.png)
![image](https://user-images.githubusercontent.com/13172977/37434008-1847d86e-27ac-11e8-95f0-1249d1acef9f.png)
![image](https://user-images.githubusercontent.com/13172977/37434018-26f054c2-27ac-11e8-8cce-d089ad566743.png)
segun la base de datos el role enterprise (id = 2 ) tiene los permisos (id 4,5,6,7)
![image](https://user-images.githubusercontent.com/13172977/37434105-7a97b35e-27ac-11e8-800d-31e8015fdd4c.png)

on the routes I have this 

![image](https://user-images.githubusercontent.com/13172977/37434149-9eb325c0-27ac-11e8-9b91-4f9cf3942d8a.png)
![image](https://user-images.githubusercontent.com/13172977/37434171-b083ebf4-27ac-11e8-88c7-40f560af1dce.png)

**Comment by jeremykenedy** [comment]
I still cannot replicate. 
https://github.com/jeremykenedy/laravel.local#important-notes

**Comment by lCHECHOl** [comment]
What I understand is that both middleware can not be here? 
![image](https://user-images.githubusercontent.com/13172977/37442532-e0091c46-27d4-11e8-8870-ca3258a54a59.png)

**Comment by lCHECHOl** [comment]
hello again, I already have the roles, and permissions and those roles associated with x permissions, now as I do so that a user with the role of the company can see the social objects, I have this:

PD: sorry if I cause discomfort or the writing is wrong, I must use the translator, thanks in advance

![image](https://user-images.githubusercontent.com/13172977/37489890-1553447a-2867-11e8-8b2e-2bfb7942301c.png)
It's supposed to be a business user, you should be able to see them, all right
![image](https://user-images.githubusercontent.com/13172977/37489947-3af2a874-2867-11e8-9940-64c4929d3e69.png)

let's see with the var_dump  "dd(var_dump(auth()->user()));"

![image](https://user-images.githubusercontent.com/13172977/37490004-6c3c8044-2867-11e8-8c31-5ff2389353bc.png)

now "dd(var_dump(auth()->user()->hasRole('enterprise')));"

![image](https://user-images.githubusercontent.com/13172977/37490051-8d6ef6b6-2867-11e8-869b-031491c963be.png)

![image](https://user-images.githubusercontent.com/13172977/37490089-acc7c20e-2867-11e8-8b14-5f4e5f4424cf.png)
![image](https://user-images.githubusercontent.com/13172977/37490106-be5fdc9a-2867-11e8-86d9-0d6a8d8cb078.png)
![image](https://user-images.githubusercontent.com/13172977/37490126-cc00410a-2867-11e8-87a9-1300688b370d.png)
![image](https://user-images.githubusercontent.com/13172977/37490166-de50e792-2867-11e8-986d-822a02d4913b.png)
![image](https://user-images.githubusercontent.com/13172977/37490195-f1566560-2867-11e8-9819-d0f5c77551af.png)
with the photos I show that the user is assigned the role of company, because I do not work the index method, now, a normal / registered user also allows me to see the social objects
