### ISSUE TITLE
RFC: roles migrations

### ISSUE THREAD

**Issue by ricardoboss** [jeremykenedy/laravel-roles#102]
First of all, nice package. Love using it!

In my latest project, I wanted to keep track of how permissions and roles change during the development and found that migrations for seeding them were a good choice.

I turned this thought into a package and would like some feedback: [ricardoboss/laravel-roles-migrations](https://github.com/ricardoboss/laravel-roles-migrations)

Do you like the idea of using migrations for managing permissions and roles?
Do you find the package useful? Is the concept clear?

Thanks!

**Comment by jeremykenedy** [comment]
That is pretty cool!

**Comment by devzakir** [comment]
Great
