### ISSUE TITLE
DefaultConnectRelationshipsSeeder filters Admin role by "name" instead of "slug"

### ISSUE THREAD

**Issue by daniel-omnistock** [jeremykenedy/laravel-roles#103]
**Describe the bug**
In https://github.com/jeremykenedy/laravel-roles/blob/master/src/Database/Seeds/DefaultConnectRelationshipsSeeder.php#L24 there is a condition filtering the Admin role by `name`. This is bad in my opinion. The condition should use the `slug` column.

We are experiencing issues with seeding now, as we changed the name for the Admin role.

**To Reproduce**
1. Change the `name` value for the Admin role in the database
2. Run the seeds via `php artisan db:seed`

**Expected behavior:**
The seeds should succesfully run, even with modified role names.

**Comment by jeremykenedy** [comment]
A Pr that is backwards compatible is welcome and I will look at it.

https://github.com/jeremykenedy/laravel-roles#opening-an-issue

Thanks!

**Comment by daniel-omnistock** [comment]
I made a PR here: https://github.com/jeremykenedy/laravel-roles/pull/104

Would it be possible for you to create a new release with it anytime soon?

**Comment by jeremykenedy** [comment]
I was out of the country and just got back. It has been released. Thanks!
