### ISSUE TITLE
Class role does not exist

### ISSUE THREAD

**Issue by LarryTX** [jeremykenedy/laravel-roles#11]
Using Laravel v. 5.6.7 with your laravel-users and laravel-roles extensions installed. make:auth has been executed as well as the associated migrations. (No other extensions installed except for what came with the initial install.) I've been over your instructions for installation for both extensions multiple times. I can't find anything that I've left off, but each time I try to go to http://<domain>/users, I get this mysterious ReflectionException (-1) Class role does not exist. Of course, the exception doesn't point to any specific place where the exception originates, except for the Illuminate classes. Ditto for the laravel.log.

I've no doubt that I'm missing something. I'm hoping that you can point me in the right direction.

**Comment by jeremykenedy** [comment]
No worries, 

Are you trying to use the `role:XXXX` middleware?

If so, I think the issue may possibly be in that the middleware is not defined in your Kernel.php

Here is an example of what I am referring to:
```
    protected $routeMiddleware = [
       ...
        'role'          => \jeremykenedy\LaravelRoles\Middleware\VerifyRole::class,
        'permission'    => \jeremykenedy\LaravelRoles\Middleware\VerifyPermission::class,
        'level'         => \jeremykenedy\LaravelRoles\Middleware\VerifyLevel::class,
      ...
```

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Kernel.php#L65

**Comment by LarryTX** [comment]
That did it! Also led me to your laravel-auth extension which I hadn't seen. Thanks for your patience.
