### ISSUE TITLE
.env Parameters duplicated

### ISSUE THREAD

**Issue by psw666** [jeremykenedy/laravel-roles#110]
'rolesAPICreateNewRolesMiddlewareType'   => env('ROLES_API_CREATE_ROLE_MIDDLEWARE_TYPE', 'role'), //permissions or roles
    'rolesAPICreateNewRolesMiddleware'       => env('ROLES_API_CREATE_ROLE_MIDDLEWARE_TYPE', 'admin'), // admin, XXX. ... or perms.XXX
    // User Permissions or Role needed to create a new permission
    'rolesAPICreateNewPermissionMiddlewareType'  => env('ROLES_API_CREATE_PERMISSION_MIDDLEWARE_TYPE', 'role'), //permissions or roles
    'rolesAPICreateNewPermissionsMiddleware'     => env('ROLES_API_CREATE_PERMISSION_MIDDLEWARE_TYPE', 'admin'), // admin, XXX. ... or perms.XXX

The env calls to duplicated  keys.

Would suggest something like:
ROLES_API_CREATE_ XXX _MIDDLEWARE_VALUE

**Comment by jeremykenedy** [comment]
I would accept a PR for this fix :)

**Comment by jeremykenedy** [comment]
These have been removed in the most recent release.

Thank you! :)
