### ISSUE TITLE
gui views do not respect the connection setting

### ISSUE THREAD

**Issue by Chris25602** [jeremykenedy/laravel-roles#112]
So I cannot give you tons of detail right now I am still looking into it but, somewhere in your 2.5.0 you are making db calls without referencing the roles.connection config. I know this because my default connection is a mssql instance and my laravel db is mysql. trying to load your roles or permissions dashboards puts an mssql error in my log. the error msg isn't that important its the fact its not using the configured db that's the issue.

The core of the package still works, ie I can check roles, levels and permissions and act on them it's just the gui part which is not functional for me. I really like this package; more so than many of the other acl packages out there. 

if you want to replicate this on your own install a blank mssql express db set it as default connection then setup your laravel db as another connection. otherwise I would be more than happy to try and implement any suggestions you might have.

**Comment by Chris25602** [comment]
In your RolesAndPermissionsHelperTrait most of your calls for basic roles and permissions are just using an ::all() so that explains it at least

**Comment by Chris25602** [comment]
looks like you need to initialize the connection prop in your model file otherwise your construct function cant actually set the value.
protected $connection = '';

**Comment by Chris25602** [comment]
alright now with the rest of the updates you 
-remove the connection prop from DatabaseTraits
-add the connection prop and constructor stmt to Permissions
-add softdelete to roles model
-modify RolesAndPermissionsHelperTrait@getPermissionsWithRoles and @getPermissionUsers
    so that query gets the right DB
$query = DB::connection(config('roles.connection'))->table(config('roles.permissionsUserTable'));

and now the gui's respect the roles.connection config

**Comment by jeremykenedy** [comment]
Would you be able to make a PR for this?

**Comment by jeremykenedy** [comment]
getPermissionsWithRoles and getPermissionUsers have been updated in the most recent release. Soft deletes exists. 

Thank you! :)
