### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionExceptio error

### ISSUE THREAD

**Issue by AYASOFT** [jeremykenedy/laravel-roles#118]
Following the install guide all works well except on the last command in the "Migrations and seeds" Part:
this is the log it throws:
```
λ php artisan db:seed
Seeding: DefaultPermissionitemsTableSeeder
Seeding: DefaultRoleItemsTableSeeder
Seeding: DefaultConnectRelationshipsSeeder
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:view.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:create.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:edit.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:delete.users

   Illuminate\Contracts\Container\BindingResolutionException

  Target class [Database\Seeds\PermissionsTableSeeder] does not exist.

  at C:\Laravel\OasisPro\vendor\laravel\framework\src\Illuminate\Container\Container.php:807
    803|
    804|         try {
    805|             $reflector = new ReflectionClass($concrete);
    806|         } catch (ReflectionException $e) {
  > 807|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    808|         }
    809|
    810|         // If the type is not instantiable, the developer is attempting to resolve
    811|         // an abstract type such as an Interface or Abstract Class and there is

  1   C:\Laravel\OasisPro\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      ReflectionException::("Class Database\Seeds\PermissionsTableSeeder does not exist")

  2   C:\Laravel\OasisPro\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      ReflectionClass::__construct()
```

Laravel Installer 3.0.1
Laravel Framework 7.5.1
npm 6.13.4
node .js 12.16.1
Material Dashboard Backend Installed.
i've tried every suggestion in issue #42 but always getting the error
the only command that goes without error is :
`php artisan db:seed --class=PermissionsTableSeeder`
thx for the support.
i hope this helps in resolving the issue.

**Comment by AYASOFT** [comment]
https://github.com/jeremykenedy/laravel-roles/issues/13#issuecomment-574855145
thx @base64bitsthis solved the problem
@jeremykenedy i think the readme should be edited to reflect the fix

**Comment by Multipage** [comment]
This fix is not working for :
Laravel Framework 8.11.2
Laravel Roles 4.0.0

I allready tried everything else mentioned all over the internet but it is stll the same:
`   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [PermissionsTableSeeder] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811`
