### ISSUE TITLE
Problem in running this package

### ISSUE THREAD

**Issue by mutahir-shah** [jeremykenedy/laravel-roles#124]
Hi,
I have fully followed all the steps of your package. I published all the dependencies . The problem now for me is how to open this project. All the routes and Controller and Model are still inside the package . How could I open a route in browser. I tried many thing but couldn't successes. Can you help me this regard.
Thanks.
Regards,
Mutahir Shah.

**Comment by jeremykenedy** [comment]
Check your config.

**Comment by mutahir-shah** [comment]
Config is not helpful.
