### ISSUE TITLE
Every role is being loaded even when one is being used?

### ISSUE THREAD

**Issue by mackensiealvarezz** [jeremykenedy/laravel-roles#126]
For some reason anytime i check if a user has a role, it automatically does two queries and loads all permissions? 

Here a screenshot from the laravel debug bar.
![Screen Shot 2020-07-07 at 10 58 06 AM](https://user-images.githubusercontent.com/6855367/86800301-e1fb3c80-c040-11ea-9363-49c367abc060.png)

Is there anything i am doing wrong? Or anyway to cache this? So these two queries don't have to run every time i check for one permission?

**Comment by jeremykenedy** [comment]
I don’t in one how you have it setup.
