### ISSUE TITLE
Permission is not working as expected

### ISSUE THREAD

**Issue by saimirballeshi** [jeremykenedy/laravel-roles#13]
Hello,
I'm facing problems on checking permissions for users in roles, it return always true even if I detach the permision from role

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles#opening-an-issue

**Comment by base64bits** [comment]
For those still having issues change in DatabaseSeeder.php

public function run()
    {
        Model::unguard();

            $this->call(PermissionsTableSeeder::class);
            $this->call(RolesTableSeeder::class);
            $this->call(ConnectRelationshipsSeeder::class);
            //$this->call('UsersTableSeeder');

        Model::reguard();
    }

To

public function run()
    {
        Model::unguard();

            $this->call('PermissionsTableSeeder');
            $this->call('RolesTableSeeder');
            $this->call('ConnectRelationshipsSeeder');
            // $this->call('UsersTableSeeder');

        Model::reguard();
    }
