### ISSUE TITLE
Show/hide is not working in Roles/Permissions Dashboard properly

### ISSUE THREAD

**Issue by haseeb40** [jeremykenedy/laravel-roles#130]
Show/Hide is implemented to show the details of users assigned to the roles and permissions in the Permissions and Roles Card. When clicking the the specific role it collapses and shows the details. tooltip with the - search icon shows but it does not hide the details.

**Comment by jeremykenedy** [comment]
Need to include the JavaScript by making sure you are including it in the correct yield tag in your app. You can configure that in your .env file or the config file
