### ISSUE TITLE
Error while inserting new roles & permission with Postgresql

### ISSUE THREAD

**Issue by shaphiro** [jeremykenedy/laravel-roles#131]
An error appears when trying to insert a a new role (or permission) under postgresql. No problems with the same installation under mysql.

**Software versions**
 - OS: Ubuntu v20.04
 - Browser Chrome v84
 - Laravel v7.21.0
 - laravel/roles v3.2.1
 - laravel/homestead v10.0.0
 - postgresql 12

**Steps to reproduce the behavior**
1. Go to http://mysite.local/roles
2. Click 'Create new role' (http://mysite.local/roles/create)
3. Fill in the form and send ...

**Full stacktrace**
`local.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "" (SQL: select count(*) as aggregate from "roles" where "name" = aaa and "id" <> ) {"userId":11,"exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: \"\" (SQL: select count(*) as aggregate from \"roles\" where \"name\" = aaa and \"id\" <> ) at /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
#0 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run()
#2 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2205): Illuminate\\Database\\Connection->select()
#3 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2193): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2688): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2194): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2615): Illuminate\\Database\\Query\\Builder->get()
#7 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2543): Illuminate\\Database\\Query\\Builder->aggregate()
#8 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(55): Illuminate\\Database\\Query\\Builder->count()
#9 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(763): Illuminate\\Validation\\DatabasePresenceVerifier->getCount()
#10 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(547): Illuminate\\Validation\\Validator->validateUnique()
#11 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(370): Illuminate\\Validation\\Validator->validateAttribute()
#12 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(401): Illuminate\\Validation\\Validator->passes()
#13 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\\Validation\\Validator->fails()
#14 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#15 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Container/Container.php(1137): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()
#16 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Container/Container.php(1101): Illuminate\\Container\\Container->fireCallbackArray()
#17 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Container/Container.php(1086): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()
#18 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Container/Container.php(707): Illuminate\\Container\\Container->fireResolvingCallbacks()
#19 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#20 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Foundation\\Application->resolve()
#21 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#22 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make()
#23 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(48): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
#24 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(28): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
#25 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
#26 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#27 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#28 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#29 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#30 /home/vagrant/code/pmx/vendor/jeremykenedy/laravel-roles/src/App/Http/Middleware/VerifyRole.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): jeremykenedy\\LaravelRoles\\App\\Http\\Middleware\\VerifyRole->handle()
#32 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#34 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#36 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#51 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#53 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#58 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#60 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#62 /home/vagrant/code/pmx/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#64 /home/vagrant/code/pmx/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#66 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#68 /home/vagrant/code/pmx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#69 /home/vagrant/code/pmx/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#70 {main}`

**Expected behavior**
roles and permissions are registered correctly

**Comment by shaphiro** [comment]
Why this issue has been closed? The problem persists even with the latest version.

Thanks

**Comment by jeremykenedy** [comment]
Read the readme.

**Comment by shaphiro** [comment]
ok I read the readme, star added ;)

I found the problem but I'm not sure how to fix it. 
Class StorePermissionRequest at lines 34 and 35

$this->id is an emprty string ($this->id === '') but it should be a NULL instead (NULL or something else but not an empty string).

Hope this helps.

Thanks.

**Comment by jeremykenedy** [comment]
This may be related to this PR.

I have not approved the PR yet because it is untested on non-Postgres instances.
