### ISSUE TITLE
Problem with show.blade.php ($user->roles)

### ISSUE THREAD

**Issue by iKyzu** [jeremykenedy/laravel-roles#132]
Hey, I got problem with the role system I followed everystep multiple times.
I checked everything I have been doing.

First I got an error that I didn't have the role 'admin' but I somehow fixed that, that's described here:
https://github.com/jeremykenedy/laravel-roles/issues/21

Now I am struggling with error about foreach. I am guessing something is wrong with the variable but I can't go where is the error.

```
ErrorException
Invalid argument supplied for foreach() (View: /home/laravel/rental/resources/views/vendor/laravelusers/usersmanagement/show-users.blade.php) 
```

**Laravel version** 7.22.4
**PHP version** 7.4.8

I don't know if it has to do something with it but I have also problem with target class that's described in another issue:
https://github.com/jeremykenedy/laravel-roles/issues/80
I can't run _php artisan db:seed_ here.

Best Regards!

**Comment by jeremykenedy** [comment]
Cannot replicate: https://github.com/jeremykenedy/laravel-roles#opening-an-issue
