### ISSUE TITLE
Distinguishable Exceptions

### ISSUE THREAD

**Issue by marcnewton** [jeremykenedy/laravel-roles#134]
My use case is a Vue App with Laravel as back-end & this package for the roles etc.

The issue I ran into is the ability to properly distinguish between an actual server exception error and a permission denied response.

Currently I receive a **500** status error JSON response from a lack of an admin role from an ajax call:

```json
{
    "message": "You don't have a required ['admin'] role."
}
```

But it is even more vague when in **production** with `APP_DEBUG=false` you just get:
```json
{
    "message": "Server Error"
}
```

I handle 500 status response codes on the client with a generic **Service Disruption** message but want to show a **Permission Denied** message for a lack of a role/permission.

My proposal is that `AccessDeniedException` should return a **403 Forbidden** header code instead of the default **500 Internal Server Error** response and/or allow easy customization of the response code and content.

Perhaps `config/roles.php` could have a config entry allowing specification of a custom `AccessDeniedException` class to load?

**Comment by marcnewton** [comment]
My current workaround is to extend `render` method of `Exception`:

```php
<?php

namespace jeremykenedy\LaravelRoles\App\Exceptions;

use Exception;

class AccessDeniedException extends Exception
{
    /**
     * Render the exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function render($request)
    {
        return response($request->wantsJson() ? ['message' => $this->getMessage()] : $this->getMessage(), 403);
    }
}
```

**Comment by jeremykenedy** [comment]
You can manage what happens:



It throws `\jeremykenedy\LaravelRoles\App\Exceptions\RoleDeniedException`, `\jeremykenedy\LaravelRoles\App\Exceptions\PermissionDeniedException` or `\jeremykenedy\LaravelRoles\App\Exceptions\LevelDeniedException` exceptions if it goes wrong.

You can catch these exceptions inside `app/Exceptions/Handler.php` file and do whatever you want.

```php
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {

        $userLevelCheck = $exception instanceof \jeremykenedy\LaravelRoles\App\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\App\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\App\Exceptions\PermissionDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\App\Exceptions\LevelDeniedException;

        if ($userLevelCheck) {

            if ($request->expectsJson()) {
                return Response::json(array(
                    'error'    =>  403,
                    'message'   =>  'Unauthorized.'
                ), 403);
            }

            abort(403);
        }

        return parent::render($request, $exception);
    }
```





https://github.com/jeremykenedy/laravel-roles#middleware

**Comment by jeremykenedy** [comment]
I am open for PR to improve upon this :)

**Comment by marcnewton** [comment]
@jeremykenedy You know in your documentation from where you copied that snippet from, you put `RoleDeniedException` twice... Is one of the lines supposed to `AccessDeniedException` or is there only supposed to be 3 listed since they extend `AccessDenidException`.

----

When you say you are open for improvement on this, do you mean improvement of the example provided in the Docs to put in `app/Exceptions/Handler.php` or my solution of making this package output an appropriate header out of the box?

It still can be overridden by users in `app/Exceptions/Handler.php` right?
