### ISSUE TITLE
Using this project

### ISSUE THREAD

**Issue by neyamt** [jeremykenedy/laravel-roles#137]
I want to use this project but i don't know how to use after USAGE step of this project, please help me.

thanks

**Comment by jeremykenedy** [comment]
It is all pretty much in the readme.

If you need some example projects here are some:


- https://github.com/jeremykenedy/laravel-auth
- https://github.com/jeremykenedy/laravel-roles-example (pretty old though)
- https://github.com/jeremykenedy/laravel-material-design
- https://github.com/jeremykenedy/larablog
- https://github.com/jeremykenedy/jeremykenedy.com
