### ISSUE TITLE
Laravel 8 and DatabaseSeeder.php - documentation tweak

### ISSUE THREAD

**Issue by PaulMcRoar** [jeremykenedy/laravel-roles#142]
Not really a bug, just a documentation issue.

I'm just installing on laravel 8, and working through what will need the odd tweak.

There's no need to edit the DatabaseSeeder.php file to run the seeds, the database seeder file will just bork out if you add what's in the example to it.

Might want to mention you need to edit config/roles.php if you want the UsersTableSeeder to run.

**Comment by hktang** [comment]
Run into the same issue here, using Laravel 8. 

First it seems the class names in the example are incorrect:

```php
/** In the examples **/
use Database\Seeds\PermissionsTableSeeder;
...

/** Correct one? **/
use Database\Seeders\PermissionsTableSeeder;
...
```

But changing Seeds to Seeders does not help. Restoring the DatabaseSeeder.php works.

**Comment by jeremykenedy** [comment]
I am up for a PR to fix. Time isn't allowing me to put time into this lately.

**Comment by PaulMcRoar** [comment]
Mad busy myself but I'll try to help out once this mad period is over WRT laravel 8 instructions

**Comment by jeremykenedy** [comment]
Thank you!
