### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by zfilip92** [jeremykenedy/laravel-roles#145]
Hi,

As far as I can tell this package doesn't support PHP8, which is a shame.
My project uses this package as well as laravel-users, neither support PHP8.
(as far as composer is concerned)

Any plans on adding support for PHP8? 

I would myself do it, but I'm sort of busy. Maybe I will have time later... .

And also.. thanks for developing these great packages!

**Comment by zfilip92** [comment]
Well,

Sorry for spam, but I forced installation like a true chad by using --ignore-platform-reqs and it seems to have worked.

Best regards,
Filip

**Comment by zfilip92** [comment]
Hi again,

Sorry for spamming, but I managed to make it work like a true chad by using --ignore-platform-reqs.. I successfully installed both laravel-roles and laravel-users packages. At first look everything seems to be working well.

**Comment by jeremykenedy** [comment]
Included in next release.
