### ISSUE TITLE
Small bug in docu leads to "Illuminate\Contracts\Container\BindingResolutionException"

### ISSUE THREAD

**Issue by pammel** [jeremykenedy/laravel-roles#148]
After calling "php artisan db:seed" I got error
Illuminate\Contracts\Container\BindingResolutionException

Easy to fix, it's only a forgotten semicolon in docu:
https://github.com/jeremykenedy/laravel-roles/blob/master/readme.md

Just add semicolon after "use Database\Seeders\PermissionsTableSeeder"

```
    <?php
    
    use Illuminate\Database\Seeder;
    use Illuminate\Database\Eloquent\Model;
    use Database\Seeders\PermissionsTableSeeder; // <-- add semicolon here 
    use Database\Seeders\RolesTableSeeder;
    use Database\Seeders\ConnectRelationshipsSeeder;

    class DatabaseSeeder extends Seeder
    ...
```

**Comment by jeremykenedy** [comment]
Fixed, thank you
