### ISSUE TITLE
Permission and Roles cannot be Deleted.

### ISSUE THREAD

**Issue by shehroz-myglu** [jeremykenedy/laravel-roles#154]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Describe the bug**
permission and roles delete button and modal not working its giving javascript error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeremykenedy** [comment]
Probably a javascript error from not including the js. 

What's the js error in the browser it gives?

**Comment by shehroz-myglu** [comment]
roles:1840 Uncaught TypeError: Cannot read property 'submit' of undefined in ===>>> resources/views/vendor/laravelroles/laravelroles/forms/confirm-modal.blade.php

**Comment by shehroz-myglu** [comment]
i have not changed anything in original code just installed on local and this is it.

**Comment by jeremykenedy** [comment]
I cannot duplicate or see an error in that script file. 

It's possible you might not have one of the following configured or your blade file you are extending off of has the needed includes in it.

see

https://github.com/jeremykenedy/laravel-roles/blob/master/src/config/roles.php#L153


https://github.com/jeremykenedy/laravel-roles/blob/b180f18a494ff8527c5dd120aca6a0515971abb5/src/config/roles.php#L155

Link to file outlined in js error reported: 
https://github.com/jeremykenedy/laravel-roles/blob/master/src/resources/views/laravelroles/scripts/confirm-modal.blade.php


Call to file:
https://github.com/jeremykenedy/laravel-roles/blob/master/src/resources/views/laravelroles/crud/dashboard.blade.php#L85

**Comment by shehroz-myglu** [comment]
as i said i havent changed anything it was the original code cloned from git everything else is working but not delete button.
YES i have placed these js files in my 
![image](https://user-images.githubusercontent.com/76989359/113441595-fc174f00-9407-11eb-994f-7803806b17f9.png)

**Comment by shehroz-myglu** [comment]
but this on.show.bs.modal is not working title message and modal body is not being changed too

**Comment by jeremykenedy** [comment]
Could be a jquery build conflict, okay the config/env settings for the package and see how it works with including and using a cdn va your built app.js. It may take some fínese to align that js. If bootstrap modal isn't even popping up it's most likely a js conflict issue.

**Comment by jeremykenedy** [comment]
Cannot replicate
