### ISSUE TITLE
Error after db:seed

### ISSUE THREAD

**Issue by hweiss24** [jeremykenedy/laravel-roles#156]
Hi, thank you for laravel-roles. I try to do the setup but with the step: php artisan db:seed i get the following error: 
 ` Illuminate\Contracts\Container\BindingResolutionException

  Target class [Database\Seeders\DatabaseSeeder] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807|
    808|         try {
    809|             $reflector = new ReflectionClass($concrete);
    810|         } catch (ReflectionException $e) {
  > 811|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812|         }
    813|
    814|         // If the type is not instantiable, the developer is attempting to resolve
    815|         // an abstract type such as an Interface or Abstract Class and there is

      +25 vendor frames
  26  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

Have you an idea why? I'm a new laravel beginner... Thanks

**Comment by jeremykenedy** [comment]
It's not the package, it's your app. You need to resolve the core seeder class and most likely it's commented out on the or your out the box DatabaseSeeder class is file is missing.

https://laravel.com/docs/8.x/seeding
