### ISSUE TITLE
Permissions by users

### ISSUE THREAD

**Issue by malletfils** [jeremykenedy/laravel-roles#159]
Hello,

I see that there is a "permission_user" table, that seems to enable to assign specific permissions to a user. But I can't find how to do it from the admin pages. And I can't find any documentation about it too. I would like to add, for example on the user edit page, a form field to assign specific permissions to the user. Can you help me do that ? Thanks.

**Comment by jeremykenedy** [comment]
You would attach/detach them:

https://github.com/jeremykenedy/laravel-roles#attaching-detaching-and-syncing-permissions
