### ISSUE TITLE
Bug in Config/Roles.php

### ISSUE THREAD

**Issue by Solotov** [jeremykenedy/laravel-roles#161]
I have found a repeating key, which causes malfunctioning of the forms for creating or editing permissions and roles.
the issue comes from this settings file:
`vendor/jeremykenedy/laravel-roles/src/config/roles.php: line 128 to 133`

### incorrect settings :
// User Permissions or Role needed to create a new role
```
'rolesGuiCreateNewRolesMiddlewareType'   => env('ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE', 'role'), 
'rolesGuiCreateNewRolesMiddleware'       => env('ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE', 'admin'),
```

// User Permissions or Role needed to create a new permission
```
'rolesGuiCreateNewPermissionMiddlewareType'  => env('ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE', 'role'), 
'rolesGuiCreateNewPermissionsMiddleware'     => env('ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE', 'admin'),
```

### suggested solution :

// User Permissions or Role needed to create a new role
```
'rolesGuiCreateNewRolesMiddlewareType'   => env('ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE', 'role'), 
'rolesGuiCreateNewRolesMiddleware'       => env('ROLES_GUI_CREATE_ROLE_MIDDLEWARE', 'admin'),
```

// User Permissions or Role needed to create a new permission
```
'rolesGuiCreateNewPermissionMiddlewareType'  => env('ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE', 'role'), 
'rolesGuiCreateNewPermissionsMiddleware'     => env('ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE', 'admin'),
```

I have solved this problem by editing the (published) config/roles.php file of my project, 
but the original package file still has the error.

Thanks,

**Comment by jeremykenedy** [comment]
Thank you
