### ISSUE TITLE
Integrating in a existing app

### ISSUE THREAD

**Issue by ugintl** [jeremykenedy/laravel-roles#162]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**
I have a fully functional invoicing management laravel 8 app. It has users and authentication system, but does not have permissions. Can I use laravel-roles to add this functionality to my existing app?

**Comment by jeremykenedy** [comment]
yes
