### ISSUE TITLE
how i can redirect user to 404 page instead of this admin page 

### ISSUE THREAD

**Issue by Omarhariri10** [jeremykenedy/laravel-roles#165]
hi , thankyou for this package , i want to ask you how by this code , redirect user to 404 page , when anyone write /admin in the domain, its show this 
![InkedIMG_20211101_054706_LI](https://user-images.githubusercontent.com/93765096/140948772-f34aea3d-2994-4bb5-a4d3-5c404b7eceda.jpg)
:
**actually i try to add a code you answered it someone ask same question, but when i add it , its give me ERR:500 , and some functionality in website stop work like report button**

actually I am beginner for that I  hope you understand my question, hope to help me to resolve this problem 👍 
this is the code : 

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Throwable  $exception
     * @return void
     *
     * @throws \Exception
     */
    public function report(Throwable $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Throwable  $exception
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \Throwable
     */
    public function render($request, Throwable $exception)
    {
        return parent::render($request, $exception);
    }
}

**Comment by jeremykenedy** [comment]
500 error is too general. Look at your laravel.log to see what the actual error is.

**Comment by Omarhariri10** [comment]
i know that , but about the problem (in image ) what should i change in the code ?
