### ISSUE TITLE
N+1 happening after PR #171

### ISSUE THREAD

**Issue by denydias** [jeremykenedy/laravel-roles#179]
**First take a look at the following**
- [x] https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
- [x] https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Describe the bug**
After PR #171 was merged and the new code hit the wild with laravel-roles v8.1.0 for L9, the project I'm working with has been plagued with N+1 warnings from [beyondcode/laravel-query-detector](https://github.com/beyondcode/laravel-query-detector). What's interesting is that the purpose of the referred PR is to fix N+1 queries. But see:

```
[2022-03-18 13:21:17] app.INFO: [BEGIN] UserStoreUpdateControllerTest  
[2022-03-18 13:21:18] app.INFO: testUpdate N+1  
[2022-03-18 13:21:18] app.INFO: Detected N+1 Query  
[2022-03-18 13:21:18] app.INFO: Model: App\Models\User
Relation: App\Models\Role
Num-Called: 2
Call-Stack:
#19 /vendor/jeremykenedy/laravel-roles/src/Traits/HasRoleAndPermission.php:49
#20 /vendor/jeremykenedy/laravel-roles/src/Traits/HasRoleAndPermission.php:145
#21 /app/Http/Controllers/Admin/UserUpdateController.php:123
```

If I manually revert [Traits\HasRoleAndPermission->getRoles()](https://github.com/jeremykenedy/laravel-roles/blob/master/src/Traits/HasRoleAndPermission.php#L45) to the old code (i.e. before PR #171)...

```php
public function getRoles()
{
    return (!$this->roles) ? $this->roles = $this->roles()->get() : $this->roles;
}
```

...then N+1 queries are gone. I'm still trying to isolate the issue, so I don't have a solution to propose just yet.

For the record, this is the relevant bits in `/app/Http/Controllers/Admin/UserUpdateController.php`:

```php
# Replaces jeremykenedy\laravelusers\App\Http\Controllers\UsersManagementController::update();

namespace App\Http\Controllers\Admin;

class UserUpdateController extends Controller
{
    public function __invoke(Request $request, int $id): RedirectResponse
    {
        $rolesEnabled = config('laravelusers.rolesEnabled');
        $user = config('laravelusers.defaultUserModel')::find($id);
        ...
        if ($rolesEnabled) {
            $user->detachAllRoles();
            $user->attachRole($request->input('role')); #21 UserUpdateController.php:123 from stack trace
        }
        ...
        return redirect('users')
            ->with('success', trans('laravelusers::laravelusers.messages.update-user-success'));
    }
}
```

User Model:

```php
namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission;

class User extends Authenticatable
{
    use HasRoleAndPermission;
    ...
}
```

**To Reproduce**
1. Install [beyondcode/laravel-query-detector](https://github.com/beyondcode/laravel-query-detector);
1. Override `UsersManagementController::update()`;
1. Update a user or run a test on the new method;
1. Look for N+1 messages as configured by `laravel-query-detector`.

**Expected behavior**
Get rid of N+1 queries.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Slackware 15 (Linux kernel 5.16.15), PHP 8.1.3, Laravel 9.5.1, Laravel Roles 8.1.0 
 - Browser: Vivaldi
 - Version: 5.1.2567.66 (Stable channel) stable (64 bits)  (Chrome/98.0.4758.136)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by denydias** [comment]
Well, after some extensive investigation, I could not find what's causing lots of N+1 when using [Traits\HasRoleAndPermission->getRoles()](https://github.com/jeremykenedy/laravel-roles/blob/master/src/Traits/HasRoleAndPermission.php#L45) after PR #171. For now I'll just accept the fact my code skills are rust or my knowledge is no up to a better solution.

As a workaround, I'm now just overriding `getRoles()` in the user model like this:

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Auth\User as Authenticatable;
use jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission;

class User extends Authenticatable
{
    use HasRoleAndPermission;
    ...
    /**
     * Overrides jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission->getRoles()
     * to avoid N+1 introduced by PR #171.
     *
     * @see https://github.com/jeremykenedy/laravel-roles/issues/179
     * @see https://github.com/jeremykenedy/laravel-roles/pull/171
     *
     * @return Collection|null
     */
    public function getRoles(): ?Collection
    {
        return (!$this->roles) ? $this->roles = $this->roles()->get() : $this->roles;
    }
}
```

N+1 are gone. That WFM now.

As I couldn't find the root causes in the package or in my code, I'll just leave this issue opened so others may have a reference and maybe provide a better solution.

**Comment by jeremykenedy** [comment]
I believe this was solved in a recent update. If it occurs again please let me know and I will re-open the issue. Thank you
