### ISSUE TITLE
Does it work with mongodb?

### ISSUE THREAD

**Issue by TresCe** [jeremykenedy/laravel-roles#18]
Hello, does this package work with mongodb? Thank you very much.

**Comment by jeremykenedy** [comment]
Not sure, give it a whirl.

**Comment by ThemesOps** [comment]
this question is old. might be helpful for others.
It is works with MongoDB. 
you need to edit 2 files.
vendor/jeremykenedy/laravel-roles/src/Models/Permission.php
vendor/jeremykenedy/laravel-roles/src/Models/Role.php

add
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

then replace model with Eloquent
