### ISSUE TITLE
Not publishing controllers and laravelrole view folder

### ISSUE THREAD

**Issue by Chemmaran** [jeremykenedy/laravel-roles#180]
Am using Laravel Framework 8.61.0
While publishing, the migrations and seeds are successfully imported , but not the controllers and view folders

Tried   " php artisan vendor:publish --tag=laravelroles"
and 
php artisan vendor:publish --tag=laravelroles-config
    php artisan vendor:publish --tag=laravelroles-migrations
    php artisan vendor:publish --tag=laravelroles-seeds
    php artisan vendor:publish --tag=laravelroles-views
    php artisan vendor:publish --tag=laravelroles-lang

**Comment by jeremykenedy** [comment]
Controllers don't get published

**Comment by jeremykenedy** [comment]
Views get published into a vendor folder.

see: 
https://github.com/jeremykenedy/laravel-roles/blob/master/src/RolesServiceProvider.php#L129
