### ISSUE TITLE
GUI - Undefined variable $slot

### ISSUE THREAD

**Issue by nekros05** [jeremykenedy/laravel-roles#188]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Describe the bug**
When trying to open the route /roles and the route /permissions, it sends the error "Undefined variable $slot".

**Screenshots**
![image](https://user-images.githubusercontent.com/111474058/206585611-2d55957a-bfb5-461e-8799-c4d2e6bf236c.png)

**Desktop**
 - OS: Windows 10
 - Browser: chrome
 - Laravel: 9.43
 - PHP: 8.1.10

**Additional context**
New laravel app + breeze.

**Comment by jeremykenedy** [comment]
That screenshot doesn't look like it's this package.

**Comment by Trungdung-code** [comment]
You need to replace $slot with @yield('content'). Because $slot is the definition of breeze layouts. I don't know why the author didn't mention use @yield('content') in the document.

**Comment by jeremykenedy** [comment]
Because this package doesn't say anything about using Laravel breeze.
