### ISSUE TITLE
Can't install the package in Laravel 10

### ISSUE THREAD

**Issue by alkoumi** [jeremykenedy/laravel-roles#192]
**Describe the bug**
Can't install the package in Laravel 10

**Expected behavior**

**Screenshots**

<img width="1571" alt="Screenshot 1444-07-16 at 5 57 24 PM" src="https://user-images.githubusercontent.com/10585943/217280871-26d0adaa-1145-4f92-a52d-f9e5eb59cad4.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC OS

**Comment by jeremykenedy** [comment]
It was just released today 😂

**Comment by jeremykenedy** [comment]
Looking at the screenshot you provided it says that the error in the dependency package.

**Comment by jeremykenedy** [comment]
There is a PR for the dependency:

https://github.com/eklundkristoffer/seedster/pull/8
