### ISSUE TITLE
Upgrade to Laravel 10 fails

### ISSUE THREAD

**Issue by daniel-omnistock** [jeremykenedy/laravel-roles#193]
When trying to upgrade to Laravel 10 I get this composer error:

```
- eklundkristoffer/seedster 5.0 requires illuminate/support 5.5.*|5.6.*|5.7.*|5.8.*|6.*|^7.0|^8.0|^9.0 -> satisfiable by illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0].
```

So, it seems like the `eklundkristoffer/seedster` dependency in the `composer.json` should be updated to `^7.0`.

**Comment by jeremykenedy** [comment]
Fixed with https://github.com/jeremykenedy/laravel-roles/pull/196
