### ISSUE TITLE
How to show GUI

### ISSUE THREAD

**Issue by Trungdung-code** [jeremykenedy/laravel-roles#200]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**

I have created layouts.app. In .env file # Roles GUI Settings i set it true but how to show GUI in `<body>`. How to know what to write in @yield('...')

**Comment by Trungdung-code** [comment]
resolve

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles#optional-gui-routes
