### ISSUE TITLE
How to customize permission table?

### ISSUE THREAD

**Issue by sunnysahijwani** [jeremykenedy/laravel-roles#201]
I would like to cusotmize permissions because I want to group Permissions. How can I do that? I could not figure out if this is already given or is this something we have to implement ourself. If we need to do this ourself then what would be the best way to go about doing it, so I can submit it to you to review?

**Comment by jeremykenedy** [comment]
You can attach permissions to roles and make a role group.

**Comment by sunnysahijwani** [comment]
Actually in my project, I have given Admin the ability to be able to create Groups by selecting the available permissions but there are some special permissions which I wanted to highlight, so I thought if I would be able to add a new column in permission that would be good but that creates issue with your files as you have applied group somewhere on permission and this column is not present in that clause.
