### ISSUE TITLE
"Undefined variable $slot" error is encountered when trying to access the GUI (/roles)

### ISSUE THREAD

**Issue by prescriptionlifeline** [jeremykenedy/laravel-roles#203]
[In lieu of being able to attach an admin role to myself](https://github.com/jeremykenedy/laravel-roles/issues/202) I thought I might edit config/roles.php to get access to the GUI without having the admin role. To that end I changed this:

```
    'rolesGuiEnabled'               => env('ROLES_GUI_ENABLED', false),

    // Enable `auth` middleware
    'rolesGuiAuthEnabled'           => env('ROLES_GUI_AUTH_ENABLED', true),

    // Enable Roles GUI middleware
    'rolesGuiMiddlewareEnabled'     => env('ROLES_GUI_MIDDLEWARE_ENABLED', true),
```
To this:

```
    'rolesGuiEnabled'               => env('ROLES_GUI_ENABLED', true),

    // Enable `auth` middleware
    'rolesGuiAuthEnabled'           => env('ROLES_GUI_AUTH_ENABLED', false),

    // Enable Roles GUI middleware
    'rolesGuiMiddlewareEnabled'     => env('ROLES_GUI_MIDDLEWARE_ENABLED', false),
```
Now when I try to access mywebsite.com/roles I get `Undefined variable $slot` from resources/views/layouts/app.blade.php:32.

Here's the surrounding code from app.blade.php:

```
        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>
```
Any ideas?

**Comment by jeremykenedy** [comment]
No enough information to go off of.

**Comment by jeremykenedy** [comment]
This look like it something within you app based on `resources/views/layouts/app.blade.php:32.`

**Comment by prescriptionlifeline** [comment]
app.blade.php is unmodified from what Laravel Breeze installed:

https://raw.githubusercontent.com/laravel/breeze/v1.28.1/stubs/default/resources/views/layouts/app.blade.php

If you do a diff between the app.blade.php that I posted and the above you get this:

```
18c18
<         <div class="min-h-screen bg-gray-100 dark:bg-gray-900">
---
>         <div class="min-h-screen bg-gray-100">
23c23
<                 <header class="bg-white dark:bg-gray-800 shadow">
---
>                 <header class="bg-white shadow">
```
No doubt that's due to the fact that when you're installing Laravel Breeze you're asked if you want dark mode or not.

Laravel Breeze isn't some third party product either - it's an official Laravel product. But, then again, if you don't support `php artisan tinker` then I guess I shouldn't be surprised that you're not supporting Laravel Breeze either.
