### ISSUE TITLE
Can not create role or permission from GUI, Laravel 10.45, PHP 8.2

### ISSUE THREAD

**Issue by D0nVitalio** [jeremykenedy/laravel-roles#204]
**Describe the bug**
Hi! I can change role names, so DB connection is ok. Problem with creating of permissions and roles. When I press "Save Role" for example, I get this:
Illuminate \ Database \ QueryException 
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "" CONTEXT: unnamed portal parameter $2 = ''
SELECT count(*) AS aggregate FROM "permissions" WHERE "name" = Play Game AND "id" <> 

The payload example:
_method: POST
_token: gFSakr4jkkEVUK2WsuFaCIBHvZMQ1aqycw
name: Play Game
slug: play.game
description: Test
model: Permission
action: save

**To Reproduce**
1. Fresh install L10, Postgres v16 and Roles
2. Try to create role on your GUI

**Desktop (please complete the following information):**
 - OS: Win10 64
 - chrome
 - Version latest

**Comment by jeremykenedy** [comment]
I cannot replicate :(
