### ISSUE TITLE
Check for role and permission in Blade

### ISSUE THREAD

**Issue by normimuc** [jeremykenedy/laravel-roles#23]
Tried to check in blade for role and permission. But it is not working.

@role('role1')  OR permission('topic.whatever')

How can i solve the check? Thanks

**Comment by shalemperez** [comment]
@normimuc how did you solved this? i am having this in the front-end:

`@role('admin') @endrole`

**Comment by jeremykenedy** [comment]
Make sure you add the middleware to your Kernal file

**Comment by shalemperez** [comment]
Found the issue ... need spaces, from this:

`
more code ...
@role('admin')
<li>
    <a href="#">item</a>
</li>
@endrole
more code ...
`
to this ...

`
more code ...

@role('admin')

<li>
    <a href="#">Item</a>
</li>

@endrole

more code ...
`

**Comment by normimuc** [comment]
The normal @role('whatever') @endrole works fine. That was not my question! ;)
Linebreaks are not necessary it works very well without linebreaks.
