### ISSUE TITLE
Getting permissions per user object

### ISSUE THREAD

**Issue by sorasanin** [jeremykenedy/laravel-roles#26]
When I attach role to user and use `$user->roles`, I get all roles that are attached to that user.
But when I attach permission to user, I do get connection in `permission_user` table but when I use `$user->permissions` I get null always.

I can get only all permissions by using `$user->getPermissions(),` but those are all within `permission_user` table and those from roles relations.

Is that supposed to work like that or not? Thanks

**Comment by sorasanin** [comment]
I found out from your other answers that it is usable as `->permissions` but inside `Traits/HasRoleAndPermission.php` method is called `userPermissions`.

**Comment by jeremykenedy** [comment]
That’s the way is supposed to be
