### ISSUE TITLE
Comparison to spatie/laravel-permission

### ISSUE THREAD

**Issue by judgej** [jeremykenedy/laravel-roles#3]
just wondering how this package compares to [spatie/laravel-permission](https://github.com/spatie/laravel-permission)?

The other package has been running for a long time, has many contributions and many eyes on it to keep it up-to-date and compatible with new versions of Laravel. My personal approach is never to reinvent the wheel where-ever possible. So does this package offer anything that `spatie/laravel-permission` does not?

**Comment by judgej** [comment]
Another thing with the older package, is that there are solutions already written to manage the roles, permissions, there relationships to each other, and their relationship to users and user groups.

**Comment by jeremykenedy** [comment]
This is not based on Spatie's version and I do not want to inherit the postcardaware.

I also had to make alot of changes to make this work and have seeds out the box.

**Comment by judgej** [comment]
Postcardware - that's a new term to me. Thanks, I just needed to understand a little more of the history, so I understand better where this project is heading.

**Comment by jeremykenedy** [comment]
Gotcha, I modify as needed in order to keep up with the Laravel codebase and bug reports.

**Comment by mailnike** [comment]
Hi, Spatie has a big issue with memory cache. Any idea how this package behaves if I have more than 200 permissions, and a custom role for each user (SaaS). So in short, each team role can add around 200+ rows in the permission-role table. I am using Spatie right now, but due to its cache management, my web page is consuming around 40+ mbs, and takes around 8-9 seconds too load. Will this package solve my problem ? :)

**Comment by jeremykenedy** [comment]
Hello, That is a really great question.

I am not 100% sure how it would handle that many. I think this would be a great case for me/us to write a unit test case :)

For performance, I'm wondering if using the [`Cache`](https://laravel.com/docs/5.6/cache) class may help you out. (If that's not what you are already doing and having issue pulling from).

Have you tried adding a Redis cache?

Thanks for the question.
