### ISSUE TITLE
Foreign Key Constraint Error (Users References)

### ISSUE THREAD

**Issue by shaheryartvs** [jeremykenedy/laravel-roles#31]
In Laravel 5.8 create users table migration use 
**

> $table->bigIncrements('id');

**
which is causing Foreign key constraint error on role_user table & permission_user table.

However converting:
**

> $table->bigIncrements('id');

**

TO 

**

> $table->increments('id');

**
will fix the problem.

**Comment by jeremykenedy** [comment]
CAnt duplicate

**Comment by mhenselin** [comment]
create a laravel 5.7 project 
install laravel-roles
run composer update 
run migrate:fresh - exception is thrown

**Comment by jeremykenedy** [comment]
You have to use an version of this package because of L5.8 compatibility. Try 1.5 or 1.4

**Comment by jeremykenedy** [comment]
I need to clarify this in the readme

**Comment by mhenselin** [comment]
I am not sure if the readme is enough 
as an update during the development process 
leads to a lot of trouble ;-)

**Comment by jeremykenedy** [comment]
It is due to a change in the dB schema in L5.8, If I put for L5.7 and below to use the older composer package call that should make it clear. I just forgot to write it out in the readme.

**Comment by jeremykenedy** [comment]
Similarly to how I have it write here:

https://github.com/jeremykenedy/laravel-users/blob/master/readme.md#installation-instructions
