### ISSUE TITLE
Return individual user roles and permissions in the same api call?

### ISSUE THREAD

**Issue by grafxflow** [jeremykenedy/laravel-roles#32]
This relates to issue [#25](https://github.com/jeremykenedy/laravel-roles/issues/25)

I have managed to get it working by using the api call on login and set the roles with vue.js 

`this.$store.state.user;`

But is there a way of returning permissions as well roles in the same api call? Currently roles work fine.

```
Route::get('/user', function (Request $request) {
    return $request->user()->with('roles')->find($request->user()->id);
})->middleware('auth:api');
```

**Comment by jeremykenedy** [comment]
Did you see this: 

https://github.com/jeremykenedy/laravel-roles/issues/27

**Comment by grafxflow** [comment]
Yes I have looked at the solution but would prefer to store them in vuejs **this.$store.state.use;**. So for example what I am returning in the api call is...

`{
    "id": 8,
    "username": "Test Name",
    "created_at": "2018-06-22 10:31:09",
    "updated_at": "2019-02-27 08:21:53",
    "roles": [
        {
            "id": 1,
            "name": "Admin",
            "slug": "admin",
            "description": "Admin Role",
            "level": 5,
            "created_at": "2019-03-06 09:06:54",
            "updated_at": "2019-03-06 09:06:54",
            "pivot": {
                "user_id": 8,
                "role_id": 1,
                "created_at": "2019-03-06 09:08:16",
                "updated_at": "2019-03-06 09:08:16"
            }
        }
    ]
}`

Is there a way in which I could include the permissions in the same call so like...

`{
"id": 8,
"username": "Test Name",<br />
    "created_at": "2018-06-22 10:31:09",
    "updated_at": "2019-02-27 08:21:53",
    "roles": [
        {
            "id": 1,
            "name": "Admin",
            "slug": "admin",
            "description": "Admin Role",
            "level": 5,
            "created_at": "2019-03-06 09:06:54",
            "updated_at": "2019-03-06 09:06:54",
            "pivot": {
                "user_id": 8,
                "role_id": 1,
                "created_at": "2019-03-06 09:08:16",
                "updated_at": "2019-03-06 09:08:16"
            }
        }
    ],
"permissions": [
        {
            ....
        }
    ]
}`

**Comment by jeremykenedy** [comment]
Is this solved?
