### ISSUE TITLE
Controller Middleware not working

### ISSUE THREAD

**Issue by shalemperez** [jeremykenedy/laravel-roles#37]
I am trying to do something like this in my constructor with no success:

`$this->middleware('role:premium.user');`
`$this->middleware('role:tenant.user')->only('index');`

The `php artisan route:list` command shows the middleware in the routes i need it, but i got a 403 in the routes.

Laravel documentation: https://laravel.com/docs/5.7/controllers#controller-middleware

**Comment by jeremykenedy** [comment]
It doesn’t work like that, see:

https://github.com/jeremykenedy/laravel-roles#middleware

**Comment by shalemperez** [comment]
My seeds are ok, now checking arround i notice that if i put this in my constructor:

`$this->middleware('role:tenant.user')->except('index','show');`

This is working but in the oposite way, this supposedly should allow all functions except "index" and "show", but what this is doing is allowing only "index" and "show".

Funny right? XD

**Comment by shalemperez** [comment]
By the way ... to make this work i set `\jeremykenedy\LaravelRoles\Middleware\VerifyRole::class,` as first in **kernel.php**, `$middlewarePriority` section.

**Comment by jeremykenedy** [comment]
I ask what the seed looks like because I see you have a .user at the end of the role, is that part of the seed?

**Comment by shalemperez** [comment]
> I ask what the seed looks like because I see you have a .user at the end of the role, is that part of the seed?

Yes, thats the slug, check the code:

```
      if (Role::where('name', '=', 'Tenant User')->first() === null) {
            $userRole = Role::create([
                'name'        => 'Tenant User',
                'slug'        => 'tenant.user',
                'description' => 'Tenant User Role',
                'level'       => 0,
            ]);
        }
```

Can this cause an issue?

**Comment by shalemperez** [comment]
I am ignoring the **Level** tag, just an FYI, all roles have level 0

**Comment by shalemperez** [comment]
Ok so ... i try this in the constructor ...

`$this->middleware('role:tenant.user')->except('index','show');`
`$this->middleware('role:admin')->except('index','create','store','show','edit','update','destroy');`

But is only taking the lower permissions, so the admin role can only access what tenant.user can, i have set levels in all ways with out success.
