### ISSUE TITLE
Auth::user()->hasPermission('view-users') giving error

### ISSUE THREAD

**Issue by ridislam** [jeremykenedy/laravel-roles#4]
(2/2) QueryException
SQLSTATE[42000]: Syntax error or access violation: 1055 'baseappnew.permissions.status' isn't in GROUP BY (SQL: select `permissions`.*, `permission_role`.`created_at` as `pivot_created_at`, `permission_role`.`updated_at` as `pivot_updated_at` from `permissions` inner join `permission_role` on `permission_role`.`permission_id` = `permissions`.`id` inner join `roles` on `roles`.`id` = `permission_role`.`role_id` where `roles`.`id` in (1) or `roles`.`level` < 5 group by `permissions`.`id`, `permissions`.`name`, `permissions`.`slug`, `permissions`.`description`, `permissions`.`model`, `permissions`.`created_at`, `permissions`.`updated_at`, `pivot_created_at`, `pivot_updated_at`)

**Comment by jeremykenedy** [comment]
Please provide more background on this and how it came to be. 

Pasting a sql exception doesn't tell a story.

**Comment by ridislam** [comment]
i solved the issue, it happened because i made a extra column in the permission table which is "status" and this column does not grouped by in the rolePermissions() method in HasRoleAndPermissions trait.

**Comment by jeremykenedy** [comment]
Ok cool. Should there be a migration to correct the column?

**Comment by ridislam** [comment]
actually i solved the issue by override the rolePermissions() method in my user model.

**Comment by ridislam** [comment]
you can add a status column for check if the permission is disabled or not, hope you got hot i meant
