### ISSUE TITLE
Is there a way to get the role a user has?

### ISSUE THREAD

**Issue by Daegarys** [jeremykenedy/laravel-roles#45]
I'm creating a table with all the users and i need to know what role each users has. Is there a way to achieve this?

**Comment by Daegarys** [comment]
I've achieved this by doing: 
`$user->roles->first()['name']`
Is there any faster way?

**Comment by jeremykenedy** [comment]
You can check out some of the methods I am working on the development branch. They might be waht you are looking for:

https://github.com/jeremykenedy/laravel-roles/blob/development/src/Traits/RolesGUITraits.php#L109

https://github.com/jeremykenedy/laravel-roles/blob/development/src/App/Http/Controllers/LaravelRolesController.php#L47

https://github.com/jeremykenedy/laravel-roles/blob/development/src/resources/views/laravelroles/crud/dashboard.blade.php#L56

https://github.com/jeremykenedy/laravel-roles/blob/development/src/resources/views/laravelroles/cards/roles-card.blade.php#L49

**Comment by Daegarys** [comment]
Thanks for your help and fast reply!
