### ISSUE TITLE
Package Migrations can not be overwrite

### ISSUE THREAD

**Issue by JohanMa4** [jeremykenedy/laravel-roles#46]
Hi @jeremykenedy we have error by trying migrate custom role_user migrations, because always the migration system takes the package migrations and not our custom migrations. How can i to configure the package to take my custom migrations?, i need this because we using multiple databases.

Regards!

**Comment by jeremykenedy** [comment]
Can you post the error?

**Comment by jeremykenedy** [comment]
Did you adjust the .env variables? 

https://github.com/jeremykenedy/laravel-roles/blob/master/.env.example

**Comment by JohanMa4** [comment]
Yeah, but there is no option in the package environment variables, cuz that variables only works for the seeders, and not for the migrations.

Actually we need to overwrite the migrations published by the package.

**Comment by jeremykenedy** [comment]
Publish the migrations and then adjust them as needed.

**Comment by JohanMa4** [comment]
What happed if i change the folder of the published migrations?, i think that migration system don't read the published migrations it correctly.

**Comment by jeremykenedy** [comment]
It reads them correctly, if you want to make a custom app outside of the larqvel structure system the. You will need to adjust accordingly and make additional modification migrations.

**Comment by jeremykenedy** [comment]
![Laravel Roles Migration][https://s3-us-west-2.amazonaws.com/github-project-images/laravel-roles/laravel-roles-custom-migration.gif]
