### ISSUE TITLE
Middleware return to view

### ISSUE THREAD

**Issue by Daegarys** [jeremykenedy/laravel-roles#47]
How do i return a user to a view if he doesn't have the required role?

```
public function render($request, Exception $exception)
    {
        $userLevelCheck = $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\PermissionDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\LevelDeniedException;

        if ($userLevelCheck) {

            $page = array(
                'name' => 'Dashboard'
            );
            
            return view('home')->with('page', $page);
        }

        return parent::render($request, $exception);
    }
```

This gives me a "Call to a member function setCookie() on null" error and i can't seem to fix it am i doing something wrong?

**Comment by jeremykenedy** [comment]
You can’t If they do not have the required role. That defeats the purpose of roles.

**Comment by Daegarys** [comment]
But the view i want to return the user to can be accessed by every role

**Comment by jeremykenedy** [comment]
Actually I think I missed understood, you would return earlier than the exceptions

**Comment by Daegarys** [comment]
But then how would i know what exception the user gets returned on?

**Comment by jeremykenedy** [comment]
You can keep your structure as is and to a `redirect('routename')`

**Comment by Daegarys** [comment]
Thanks for the quick responses!
