### ISSUE TITLE
Question for multiple roles

### ISSUE THREAD

**Issue by adam-devapp** [jeremykenedy/laravel-roles#48]
Question: Paired with your user management extension, is there a simple way to enable multiple role selection on the create/edit form. The default showing is 1, and I can't find a trait or similar listed to enable multiple roles on the blade templates.

I noticed the form didn't have:
multiple="multiple"

<select class="custom-select form-control" name="role" id="role" multiple="multiple">

**Comment by jeremykenedy** [comment]
Hello,

No there is not, you have to alternative options:

1. Create a role with the permissions you want and do checks on permissions.
2. Create a role with the levels and check on the level.

Currently, there are no shared roles.

Thank you,
