### ISSUE TITLE
Class 'App\UserRole' not found

### ISSUE THREAD

**Issue by N3rdP1um23** [jeremykenedy/laravel-roles#50]
I'm using Laravel 5.8 and just added this package to my project.  I tried to add the section that adds the user and the role on registration and I'm getting an issue.  Laravel is stating that

**Class 'App\UserRole' not found**

Occurred in **vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasRelationships.php** on line 720.

Has anyone else had this issue and been able to solve it?

**Comment by jeremykenedy** [comment]
Something is malformed with your class call, UserRole doesn’t exist.

**Comment by jeremykenedy** [comment]
See https://github.com/jeremykenedy/laravel-roles#assign-a-user-role-to-new-registered-users

And make sure your .env is configured correctly.

**Comment by N3rdP1um23** [comment]
Yeah, I noticed that and I don't have a UserRole Class.  I made sure that everything is correct.

I just ran all or the cache clears through artisan and composer for the fourth time and it's working now haha.
