### ISSUE TITLE
HasRolesAndPermissions rolePermissions() is missing 'deleted_at' in its groupBy

### ISSUE THREAD

**Issue by aftek** [jeremykenedy/laravel-roles#56]
Hello !

Just tried this awesome looking package for laravel ( thanks ! )
according to my composer.lock, i'm using 2.0.1

Quickly first, the database seeds aren't working out of the box,
saying that the seeder classes were not found..
had to remove the `namespace Database\Seeders` to have it working.
( note that `php artisan make:seed` creates a new file without any namespace )

Then seeding works but still not for `UsersTableSeeder`
I'd get a ` Syntax error or access violation: 1055 'mydb.permissions.deleted_at' isn't in GROUP BY`

narrowed it down to the `HasRoleAndPermission->rolePermissions()` method..
as the sql error said, simply adding 'permissions.deleted_at' to the `groupBy` fixed it for me:

```php
trait HasRoleAndPermission
{
    [ ... ]

    public function rolePermissions()
    {
        $permissionModel = app(config('roles.models.permission'));

        if (!$permissionModel instanceof Model) {
            throw new InvalidArgumentException('[roles.models.permission] must be an instance of \Illuminate\Database\Eloquent\Model');
        }

        return $permissionModel
            ::select(['permissions.*', 'permission_role.created_at as pivot_created_at', 'permission_role.updated_at as pivot_updated_at'])
            ->join('permission_role', 'permission_role.permission_id', '=', 'permissions.id')
            ->join('roles', 'roles.id', '=', 'permission_role.role_id')
            ->whereIn('roles.id', $this->getRoles()->pluck('id')->toArray())
            ->orWhere('roles.level', '<', $this->level())
            ->groupBy(['permissions.id', 'permissions.name', 'permissions.slug', 'permissions.description', 'permissions.model', 'permissions.created_at', 'permissions.updated_at', 'permissions.deleted_at', 'pivot_created_at', 'pivot_updated_at' ]);
    }

    [ ... ]
}
```

.. now, back to enjoying this package :)

**Comment by jeremykenedy** [comment]
Odd, I cannot replicate these issues. I can get the seeds to work fine out of the box. 

What OS are you using and what the environment look like you are on?

**Comment by Aftek** [comment]
I'm using an Ubuntu 18.04.2 virtualbox vm.

MariaDB 10.3.15 and PHP 7.2.17
other than adding the repo for mariadb 10.3, it's default configuration from its install.

Just verified, and strict mode is activated with "STRICT_TRANS_TABLES"

> Strict mode. Statements with invalid or missing data are aborted and rolled back, except that for non-transactional storage engines and statements affecting multiple rows where the invalid or missing data is not the first row, MariaDB will convert the invalid value to the closest valid value, or, if a value is missing, insert the column default value. Default since MariaDB 10.2.4.

https://mariadb.com/kb/en/library/sql-mode/


Not sure why about the database seeds though..
I just mimicked the `php artisan make:seed` which creates them without namespace.

**Comment by jeremykenedy** [comment]
I cannot replicate the issue with the seeds. The namespace is part of the files intentionally to avoid a collision from the default built-in seeds.

**Comment by jeremykenedy** [comment]
I also was able to get it to seed the default users table normally as well.

**Comment by jeremykenedy** [comment]
Able to reproduce on production system.

**Comment by jeremykenedy** [comment]
Fixed https://github.com/jeremykenedy/laravel-roles/releases/tag/v2.1.0
