### ISSUE TITLE
List assigned roles and permissions for an object

### ISSUE THREAD

**Issue by 06chaynes** [jeremykenedy/laravel-roles#6]
How you would recommend we pull an array of assigned roles and permissions for an object?

**Comment by jeremykenedy** [comment]
Hi,
Thanks for the questions. 

You should be able to call the Model in the head of the class you are working in
 and then do a query using eloquent.

Head call

```
use jeremykenedy\LaravelRoles\Models\Role;
use jeremykenedy\LaravelRoles\Models\Permission;
```

Calls you would use within your method to retrieve all the Roles and Permissions:

```
$permissions = Permission::all();
$roles = Role::all();
```

Then the pseudo code to combine the collections would be something like:
`
$merged = $permissions->merge($roles); 

`

**Comment by 06chaynes** [comment]
So this did provide what I needed however I do notice an issue with the slug. When I check the contents of `$user->roles` I see that the `slug` field is not properly formatted. My slug is set to `implicit_rights` however the array shows as `implicitrights` without the underscore.

**Comment by 06chaynes** [comment]
Sorry, just realized my mistake. The slug needs to be a period, not underscore. I'll go ahead and close this issue, thanks again.
