### ISSUE TITLE
Can't save new permissions or roles

### ISSUE THREAD

**Issue by emilioM16** [jeremykenedy/laravel-roles#60]
Hi, as the title says, i can't save a new role or permissions. It apperars that is passing a empty string to the id field and i can't figure out the problem. I'm kind of new in laravel so any help would be appreciated. 
![Screenshot_20190620_160256](https://user-images.githubusercontent.com/23036462/59884488-e483e900-938e-11e9-8d21-6476145b8d56.png)

**Comment by jeremykenedy** [comment]
I cannot replicate this issue. From the screen you provided it looks like an issue with your connection to your database.

https://github.com/jeremykenedy/laravel-roles#opening-an-issue
