### ISSUE TITLE
Use the Optional GUI Routes  

### ISSUE THREAD

**Issue by cyrilmanuel** [jeremykenedy/laravel-roles#62]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**

hi, thank you so much for this project. i really want to use you gui to manage roles user and perm. but i don't know how it's work. can you help me to use them on my project ?? 

thank's you

**Comment by jeremykenedy** [comment]
Configure these in your .env file:

```
# Roles GUI Settings
ROLES_GUI_ENABLED=true
ROLES_GUI_AUTH_ENABLED=true
ROLES_GUI_MIDDLEWARE_ENABLED=true
ROLES_GUI_MIDDLEWARE='role:admin'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='admin'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='admin'
ROLES_GUI_BLADE_EXTENDED='layouts.app'
ROLES_GUI_TITLE_EXTENDED='template_title'
ROLES_GUI_LARAVEL_ROLES_ENABLED=false
ROLES_GUI_TOOLTIPS_ENABLED=true
ROLES_GUI_DATATABLES_JS_ENABLED=false
```

https://github.com/jeremykenedy/laravel-roles#opening-an-issue
