### ISSUE TITLE
GUI Attach User

### ISSUE THREAD

**Issue by cyrilmanuel** [jeremykenedy/laravel-roles#64]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
The GUI to manage roles and permissions is perfect, but the only one things we can't do, is manage user to attach them to a Roles.

**Describe alternatives you've considered**
i have installed laravel-users but we can't do this.

**Comment by jeremykenedy** [comment]
You have to configure that package too. Look at the end options for that package too.
