### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by yanchespenda** [jeremykenedy/laravel-roles#74]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Is your feature request related to a problem? Please describe.**
I can't update my laravel project from 5.8 to 6.0 because laravel-roles doesn't support laravel 6.0

**Comment by jeremykenedy** [comment]
It hasn't been added yet.

L6 only released today.
