### ISSUE TITLE
Laravel 6.0.1 / Call to undefined function jeremykenedy\LaravelRoles\Traits\starts_with()

### ISSUE THREAD

**Issue by pboese** [jeremykenedy/laravel-roles#75]
Hi! 

I'm using your awesome project already with laravel 5.7 and 5.8 without any issues. Thanks a lot for that!

With a freshly installed laravel 6.0.1 I am getting the following error when opening /roles

> (1/1) Error
> Call to undefined function jeremykenedy\LaravelRoles\Traits\starts_with()
> 
> in HasRoleAndPermission.php line 438
> at User->callMagic('hydrate', array(array(object(stdClass))))
> in HasRoleAndPermission.php line 451
> at User->__call('hydrate', array(array(object(stdClass))))
> in Builder.php line 521
> at Builder->getModels(array('*'))
> in Builder.php line 505
> at Builder->get(array('*'))
> in BuildsQueries.php line 143
> at Builder->first()
> in EloquentUserProvider.php line 52
> at EloquentUserProvider->retrieveById(1)
> in SessionGuard.php line 131
> at SessionGuard->user()
> in AuthManager.php line 54
> at AuthManager->Illuminate\Auth\{closure}(null)
> at call_user_func(object(Closure), null)
> in AuthServiceProvider.php line 84
> at AuthServiceProvider->Illuminate\Auth\{closure}(null)
> at call_user_func(object(Closure), null)
> in Request.php line 517
> at Request->user()
> in LaravelRequestContext.php line 20
> at LaravelRequestContext->getUser()
> in LaravelRequestContext.php line 68
> at LaravelRequestContext->toArray()
> in Report.php line 187
> at Report->allContext()
> in AnonymizeIp.php line 11
> at AnonymizeIp->handle(object(Report), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Report))
> in AddGlows.php line 24
> at AddGlows->handle(object(Report), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Report))
> in Pipeline.php line 105
> at Pipeline->then(object(Closure))
> in Flare.php line 174
> at Flare->createReport(object(FatalThrowableError))
> in ErrorPageHandler.php line 38
> at ErrorPageHandler->handle(object(FatalThrowableError))
> in IgnitionWhoopsHandler.php line 25
> at IgnitionWhoopsHandler->handle(object(FatalThrowableError))
> in Run.php line 321
> at Run->handleException(object(FatalThrowableError))
> in Handler.php line 345
> at Handler->renderExceptionWithWhoops(object(FatalThrowableError))
> in Handler.php line 324
> at Handler->renderExceptionContent(object(FatalThrowableError))
> in Handler.php line 308
> at Handler->convertExceptionToResponse(object(FatalThrowableError))
> in Handler.php line 287
> at Handler->prepareResponse(object(Request), object(FatalThrowableError))
> in Handler.php line 192
> at Handler->render(object(Request), object(FatalThrowableError))
> in Handler.php line 49
> at Handler->render(object(Request), object(FatalThrowableError))
> in Pipeline.php line 51
> at Pipeline->handleException(object(Request), object(FatalThrowableError))
> in Pipeline.php line 178
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in VerifyCsrfToken.php line 75
> at VerifyCsrfToken->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in StartSession.php line 56
> at StartSession->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in EncryptCookies.php line 66
> at EncryptCookies->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in Pipeline.php line 105
> at Pipeline->then(object(Closure))
> in Router.php line 682
> at Router->runRouteWithinStack(object(Route), object(Request))
> in Router.php line 657
> at Router->runRoute(object(Request), object(Route))
> in Router.php line 623
> at Router->dispatchToRoute(object(Request))
> in Router.php line 612
> at Router->dispatch(object(Request))
> in Kernel.php line 176
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
> in Pipeline.php line 130
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in TransformsRequest.php line 21
> at TransformsRequest->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in TransformsRequest.php line 21
> at TransformsRequest->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in ValidatePostSize.php line 27
> at ValidatePostSize->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in CheckForMaintenanceMode.php line 62
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in TrustProxies.php line 57
> at TrustProxies->handle(object(Request), object(Closure))
> in Pipeline.php line 171
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> in Pipeline.php line 105
> at Pipeline->then(object(Closure))
> in Kernel.php line 151
> at Kernel->sendRequestThroughRouter(object(Request))
> in Kernel.php line 116
> at Kernel->handle(object(Request))
> in index.php line 55
> 

 - OS: MacOS 10.14.6
 - Browser Chrome 76
 - Laravel version 6.0.1 on Homestead with nginx/1.15.8 and PHP 7.3.8

**Comment by amalbhalbe** [comment]
add following to your composer.json
"laravel/helpers": "^1.1"

it fixed the problem for me, as seen here: 
https://github.com/m-rufflesmcghie/larablog-1/pull/5/files

they had same problem

**Comment by jeremykenedy** [comment]
Thank you!
