### ISSUE TITLE
Override migrations

### ISSUE THREAD

**Issue by Firtzberg** [jeremykenedy/laravel-roles#76]
Since https://github.com/jeremykenedy/laravel-roles/commit/d137fee4270a9b465b1509e3dfcdcc7d3b9f574c package migrations get properly loaded. Since this is not optional (conditional) this cannot be prevented.
After publishing migrations with `php artisan vendor:publish --tag=laravelroles-migrations` it is not possible to migrate since it leads to a "Cannot declare class CreateRolesTable, because the name is already in use" error. In my case I was modifying the name of the migration file.

A possible solution would be to make loading of migrations optional (configurable from env file). Also when publishing the migrations let the user know they should disable it after publishing the migrations.

**Comment by jeremykenedy** [comment]
If the migrations are present after you publish them they will override them. The name of the file is important so it shouldn’t be changed.

**Comment by Firtzberg** [comment]
I've got to change the filename. The date of the roles migration has to be in 2019, cannot be 2016.
