### ISSUE TITLE
GUI does not work

### ISSUE THREAD

**Issue by ThemesOps** [jeremykenedy/laravel-roles#78]
I enabled GUI and cleaned my cache. When I go to url  `prjectname/roles`  page coming as blank

.env file
```
# Roles GUI Settings
ROLES_GUI_ENABLED=true
ROLES_GUI_AUTH_ENABLED=true
ROLES_GUI_MIDDLEWARE_ENABLED=true
ROLES_GUI_MIDDLEWARE='role:admin'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='admin'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='admin'
ROLES_GUI_BLADE_EXTENDED='layouts.app'
ROLES_GUI_TITLE_EXTENDED='template_title'
ROLES_GUI_LARAVEL_ROLES_ENABLED=true
ROLES_GUI_TOOLTIPS_ENABLED=true
ROLES_GUI_DATATABLES_JS_ENABLED=true
```

Laravel version 5.8

I did following command. but no luck

```
composer dump-autoload
php artisan config:clear
php artisan config:cache
```

**Comment by jeremykenedy** [comment]
blank?

what does your error log say?

**Comment by ThemesOps** [comment]
blank white screen. no any error in log

**Comment by jeremykenedy** [comment]
I am unable to reproduce this error.

**Comment by ThemesOps** [comment]
I'm using this package with MongoDB. Is that cause the issue? but, all other features are working. only gui not working.

**Comment by jeremykenedy** [comment]
I still cannot reproduce the error. A blank white screen is not enough to go one while I can get it run.

**Comment by ThemesOps** [comment]
ok. I found the issue in my layout file.
it was `@yield('main-content')`

I changed it to `@yield('content')`

**Comment by ThemesOps** [comment]
Thank you for you great work and time.
