### ISSUE TITLE
Failed check for roles.deleted_at column

### ISSUE THREAD

**Issue by felixpenrose** [jeremykenedy/laravel-roles#79]
I've just updated to Laravel `6.0.3` (from `5.8`) and laravel-roles `2.2.2` (from `^1.2`)
Running on CentOS 6, PHP 7.3.9

In a blade template I have the following code to show/hide a section based on if the user is logged in and is an admin.
```
@if (Auth::check() && Auth::user()->hasRole('admin'))
```

This causes the following SQL error;

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'roles.deleted_at' in 'where clause'
(SQL:
select `roles`.*,
    `role_user`.`user_id` as `pivot_user_id`,
    `role_user`.`role_id` as `pivot_role_id`,
    `role_user`.`created_at` as `pivot_created_at`,
    `role_user`.`updated_at` as `pivot_updated_at`
from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id`
where `role_user`.`user_id` = 1
    and `roles`.`deleted_at` is null
)
```

I can't see any code in the existing migrations or those in the vendor folder that include `softDeletes` on the `roles` table.

This was working fine before the update, is there an upgrade path I've maybe missed to fix this, or is this a legitimate bug?

**Comment by felixpenrose** [comment]
Actually now just re-checking I see that the vendor folder does indeed include softDeletes
```
if (!$tableCheck) {
    Schema::connection($connection)->create($table, function (Blueprint $table) {
        $table->increments('id')->unsigned();
        $table->string('name');
        $table->string('slug')->unique();
        $table->string('description')->nullable();
        $table->integer('level')->default(1);
        $table->timestamps();
        $table->softDeletes();
    });
}
```

Is there a recommended upgrade path to add this column? Should I just create my own migration file to add this?

**Comment by jeremykenedy** [comment]
You may need to make a migration to add the deleted_at column to the table.
