### ISSUE TITLE
Target class [Database\Seeds\PermissionsTableSeeder] does not exist

### ISSUE THREAD

**Issue by sigmarhophi** [jeremykenedy/laravel-roles#80]
Fresh install of laravel 6.0 with fresh install of laravel-roles 2.2 running on linux mint.

Was following instructions and executed the following:
composer dump-autoload
php artisan db:seed

seemed to be working

```
Seeding: DefaultPermissionitemsTableSeeder
Seeding: DefaultRoleItemsTableSeeder
Seeding: DefaultConnectRelationshipsSeeder
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:view.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:create.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:edit.users
Seeding: DefaultConnectRelationshipsSeeder - Role:Admin attached to Permission:delete.users
```

then errors out with:
```
Illuminate\Contracts\Container\BindingResolutionException  : Target class [Database\Seeds\PermissionsTableSeeder] does not exist.

  at /var/www/html/concept/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
    802|
    803|         try {
    804|             $reflector = new ReflectionClass($concrete);
    805|         } catch (ReflectionException $e) {
  > 806|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    807|         }
    808|
    809|         // If the type is not instantiable, the developer is attempting to resolve
    810|         // an abstract type such as an Interface or Abstract Class and there is

  Exception trace:

  1   ReflectionException::("Class Database\Seeds\PermissionsTableSeeder does not exist")
      /var/www/html/concept/vendor/laravel/framework/src/Illuminate/Container/Container.php:804

  2   ReflectionClass::__construct("Database\Seeds\PermissionsTableSeeder")
      /var/www/html/concept/vendor/laravel/framework/src/Illuminate/Container/Container.php:804

  Please use the argument -v to see more details.
```

The seeder file seems to be present. I have checked all file permissions.

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles/issues/42

https://github.com/jeremykenedy/laravel-roles#opening-an-issue

**Comment by Lucho1976** [comment]
Same problem, have you solved this?

**Comment by expired-brain** [comment]
*In your case, 
1 . Move all seeder files from previous `database/seeds` directory to `database/seeders` folder, 
2. Remove all seeder class import, like this line _`use Database\Seeds\PermissionsTableSeeder;`_  from DatabaseSeeder.php,
3 Then run `composer dump-autoload`.*

----

Remember, from **`laravel 8`** seeders and factories are namespaced
-------------------------------------------------------------------

To accommodate for these changes, 

[1] - Add `Database\Seeders` namespace to your seeder classes.

     namespace Database\Seeders;

[2] - Move all seeder files to `database/seeders` folder.

[3] - If you import any seeders classes in `DatabaseSeeder` file then remove all of them. (*simply remove all lines that started with *`use Database\Seeders\...`* from DatabaseSeeder.php*)

[4] - Finally run `dump-autoload`.

    composer dump-autoload

---- 
***You can now try a fresh migration with seed,***

    php artisan migrate:fresh --seed

**Comment by jeremykenedy** [comment]
You need to install a pre Laravel 8 update for 7 and below: 

```
composer require jeremykenedy/laravel-roles:3.3.0
```
