### ISSUE TITLE
[Proposal] Handling N+1

### ISSUE THREAD

**Issue by raiika** [jeremykenedy/laravel-roles#82]
This package cant handle n+1 problems

    $users = User::with('roles')->get(); //query to database + eager loading
    foreach ($users as $user) {
        $user->hasRole('admin'); //looping query to database
    }

**Solution**

    /**
     * Get all roles as collection.
     *
     * @return Collection
     */
    public function getRoles()
    {
        $this->loadMissing('roles');
        
        return $this->roles ?: $this->roles = $this->getRelation('roles');
    }

**Comment by Firtzberg** [comment]
Those are 2 queries as well.

**Comment by raiika** [comment]
It's for handling this package which called "cache" without using additional trait property.

If already loaded with eager loading, it wont query again.

**Comment by raiika** [comment]
@Firtzberg I updated my statement to make it clear.
