### ISSUE TITLE
Using laravel-roles with Sentinel

### ISSUE THREAD

**Issue by Pythagus** [jeremykenedy/laravel-roles#85]
Hi,
I am using Sentinel in my project, and I wanted to use laravel-roles for managing roles.
But, all provider directives use Auth::user() for searching current user.
I would like to know if it is possible to change this user to replace by Sentinel::check()

Thanks

**Comment by jeremykenedy** [comment]
Only the model can be specified https://github.com/jeremykenedy/laravel-roles/blob/master/.env.example#L2
