### ISSUE TITLE
No query results for model [jeremykenedy\LaravelRoles\Models\Role] 4

### ISSUE THREAD

**Issue by saulmoralespa** [jeremykenedy/laravel-roles#86]
For a user not created with "DatabaseSeeder", the following problem occurs: No query results for model [jeremykenedy \ LaravelRoles \ Models \ Role] 4
[No query results for ](https://prnt.sc/pg7zn4)

You are always making a query to the role table, looking for id 4, which does not exist:
select * from `roles` where `roles`.`id` = 4 and `roles`.`deleted_at` is null limit 1

[query](https://prnt.sc/pg812l)

**Comment by jeremykenedy** [comment]
I can get it to work fine. You are not attaching the roles upon user creation. Check your implementation on your user model and user creation.

**Comment by saulmoralespa** [comment]
$userRole = config('roles.models.role')::where('name', '=', 'User')->first();
        $adminRole = config('roles.models.role')::where('name', '=', 'Admin')->first();
        $permissions = config('roles.models.permission')::all();

        /*
         * Add Users
         *
         */
        if (config('roles.models.defaultUser')::where('email', '=', 'admin@admin.com')->first() === null) {
            $newUser = config('roles.models.defaultUser')::create([
                'name'     => 'Admin',
                'email'    => 'admin@admin.com',
                'password' => bcrypt('password'),
            ]);

            $newUser->attachRole($adminRole);
            foreach ($permissions as $permission) {
                $newUser->attachPermission($permission);
            }
        }

**Comment by jeremykenedy** [comment]
Works fine here:

https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php#L116

**Comment by jeremykenedy** [comment]
And roles for users are held on a pivot table

**Comment by jeremykenedy** [comment]
fyi:
https://github.com/jeremykenedy/laravel-roles#opening-an-issue
