### ISSUE TITLE
Use a nother guard instead of auth

### ISSUE THREAD

**Issue by dukenst2006** [jeremykenedy/laravel-roles#87]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**
Great package, I'm working on a multi-tenant application where i use multi guard so how to use a specific guard instead of auth guard.
Thanks

**Comment by jeremykenedy** [comment]
You can try changing it in the env.

https://github.com/jeremykenedy/laravel-roles/blob/master/readme.md#environment-file

**Comment by dukenst2006** [comment]
There is no variable in the environment-file relate to the guard. before post that i checked it.
Thanks.

**Comment by jeremykenedy** [comment]
ROLES_GUI_MIDDLEWARE

**Comment by dukenst2006** [comment]
Thanks for you reply, Here is what i mean: 
`//if ($this->auth->check() && $this->auth->user()->hasRole($role))  ` 
Throw exceptions that i have not role admin, however have it. 
When i replace the above code by below one it's work
`if (Auth::guard('admin')->check() && Auth::guard('admin')->user()->hasRole($role))`

There is any way to prefix the GUI url like admin/roles , admin/permissions etc  ?

Thanks once again.

**Comment by BechirAhmed** [comment]
Any solution for this issue??

**Comment by jeremykenedy** [comment]
No, it uses Laravel built-in authentication system.

**Comment by jeremykenedy** [comment]
```

    /**
     * Handle an incoming request.
     *
     * @param Request    $request
     * @param \Closure   $next
     * @param int|string $role
     *
     * @throws RoleDeniedException
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $role)
    {
        if ($this->auth->check() && $this->auth->user()->hasRole($role)) {
            return $next($request);
        }

        throw new RoleDeniedException($role);
    }
```

**Comment by BechirAhmed** [comment]
So the only solution for now is to edit core package??
No suggestions??

**Comment by jeremykenedy** [comment]
It is not on the road map to step away from the built-in authentication guards, there are a lot of ramifications that can come with that and this wasn't built with not using Laravel's authentication system.

You can always for the package and tailor it to your needs then override the call in composer.json to reach out to your fork instead.

Here is a recent example where I have had to do that on another package in a project:

Example:
Call to package I need but needed it changed:
https://github.com/jeremykenedy/laravel-auth/blob/master/composer.json#L37

Having composer use my fork instead:
https://github.com/jeremykenedy/laravel-auth/blob/master/composer.json#L51

**Comment by jeremykenedy** [comment]
`VerifyRole.php` checks on the role, not permission.

**Comment by BechirAhmed** [comment]
Thanks for your suggestions
