### ISSUE TITLE
Creating a role or permission results in 403

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [jeremykenedy/laravel-roles#89]
Hi,

When I try to create a role or permission in CRUD dashboard I end up being redirected to /roles or /permissions with a 403: permission denied.

I used 3 migrations which seed the database with the following:
1. Create 3 roles: admin, user, customer
2. Create 4 permissions: view.dashboard, view.projects, view.customers, edit.profile
3. Get all permissions and attach them all to the admin role

I can open the dashboard, I can open both create and/or edit screens, but when updating or inserting it shows 403.

Any idea? I'm using laravel 5.8, laravelroles 2.3.0

**Comment by jeremykenedy** [comment]
The issue is in the 403. You do not have the needed role as specified in the env/config file. 

The user you are needs the role

**Comment by jeroenbalk-adwise** [comment]
I'm admin, and all the permissions available are attached to that role.
