### ISSUE TITLE
update to support Laravel 5.6

### ISSUE THREAD

**Issue by triblax** [jeremykenedy/laravel-roles#9]
Hi, can you update it for support Laravel 5.6, please?

**Comment by evaldobarbosa** [comment]
Clone the repository at the root of your application and add the path in the "psr-4" section of your composer.json. After that, follow the README.

**Comment by stephenmunabo** [comment]
Please update ..Thanks Mucho

**Comment by jeremykenedy** [comment]
I am going to try to get this done within the next day. Thanks.

**Comment by stephenmunabo** [comment]
You are awesome, thanks so much for your quick response
