### ISSUE TITLE
Suggestion: using the eloquent model instead of query builder

### ISSUE THREAD

**Issue by benholz** [jeremykenedy/laravel-roles#90]
Why not create references to your models rather than use `config('roles.models.role')::find($roleId);`

This enables us to use route model binding which is pretty handy in the controllers.

`Route::post('user/{user}/role/{role}','UserController@setRole’);`

```
use jeremykenedy\LaravelRoles\Models\Role as Role;

class UserController extends Controller

{

 public function setRole(User $user, Role $role)

 {

    $user->detachAllRoles();

    $user->detachAllPermissions();

    $user->attachRole($role);

    return Response::success(new RoleResource($user->getRoles()->first()));

 }

}
```

**Comment by jeremykenedy** [comment]
Flexibility for others to change the model to thier own.
