### ISSUE TITLE
Creating a role or permission results in 403 [2]

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [jeremykenedy/laravel-roles#91]
I'm sorry, you already closed my previous thread:
https://github.com/jeremykenedy/laravel-roles/issues/89

The right role (admin) is attached to my user (user_id: 1). I checked that, and I can access the CRUD dashboard, I can GET the create role/permission route, but as soon as it posts the new role or permission it results in 403.

What's the best way to narrow this down? What do I have to provide?

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles#opening-an-issue
