### ISSUE TITLE
Check roles (edit.page) don't use a table in config

### ISSUE THREAD

**Issue by MacFlay** [jeremykenedy/laravel-roles#93]
return don't use a config table

# Roles database information
ROLES_DATABASE_CONNECTION=null
ROLES_ROLES_DATABASE_TABLE=users_roles
ROLES_ROLE_USER_DATABASE_TABLE=role_user
ROLES_PERMISSIONS_DATABASE_TABLE=users_permissions
ROLES_PERMISSION_ROLE_DATABASE_TABLE=permission_role
ROLES_PERMISSION_USER_DATABASE_TABLE=users_permission_user

and if I change ROLES_ROLE_USER_DATABASE_TABLE and ROLES_PERMISSION_ROLE_DATABASE_TABLE add prefix there is a mistake too

**Comment by jeremykenedy** [comment]
Just remove it from the .env and it will default to the models.

**Comment by MacFlay** [comment]
it doesn't use the configuration in the .env file but just pulls the files from the default configuration and skips the prefix it wants to use
