### ISSUE TITLE
Error to check roles

### ISSUE THREAD

**Issue by MacFlay** [jeremykenedy/laravel-roles#94]
Hello,
I changed the database settings in the same way as in the .env file, I attach below.

When I try to check @permission ('orders.edit') on template file, the script returns a database query error.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.felis_role_user' doesn't exist (SQL: select `felis_users_roles`.*, `felis_role_user`.`user_id` as `pivot_user_id`, `felis_role_user`.`role_id` as `pivot_role_id`, `felis_role_user`.`created_at` as `pivot_created_at`, `felis_role_user`.`updated_at` as `pivot_updated_at` from `felis_users_roles` inner join `felis_role_user` on `felis_users_roles`.`id` = `felis_role_user`.`role_id` where `felis_role_user`.`user_id` = 1 and `felis_users_roles`.`deleted_at` is null) 

Where do I still need to change the database name to get the correct name from the .env and configa files with the prefix users_role_user and not role_user

# My file .env
# Roles database information
ROLES_DATABASE_CONNECTION=null
ROLES_ROLES_DATABASE_TABLE=users_roles
ROLES_ROLE_USER_DATABASE_TABLE=users_role_user
ROLES_PERMISSIONS_DATABASE_TABLE=users_permissions
ROLES_PERMISSION_ROLE_DATABASE_TABLE=users_permission_role
ROLES_PERMISSION_USER_DATABASE_TABLE=users_permission_user

**Comment by jeremykenedy** [comment]
The pivot tables. Please read the readme on opening an issue before opening another one.
