### ISSUE TITLE
[Question] Get name of the role from user

### ISSUE THREAD

**Issue by legomannetje** [jeremykenedy/laravel-roles#96]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**
Is there a way to get the name of role that a user has?
Something like $user->getRole()

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel-roles/blob/master/src/Traits/HasRoleAndPermission.php
